version: '3'
services:
  scylla-app:
    restart: always
    build:
      context: .
    networks:
      - kafka-network
    ports:
      - 8000:8000
networks:
  kafka-network:
    external:
      name:   kafka_kafka-network
