version: '3'
services:
  scylla-app:
    restart: always
    build:
      context: .
    depends_on:
      - scylla
    networks:
      - kafka-network
networks:
  kafka-network:
    external:
      name:   kafka_kafka-network
