version: '3'

services:
  accuracy_evaluator:
    command: 'python3 accuracy_evaluator.py'
    build: .
    networks:
      - kafka-network

networks:
  kafka-network:
    external:
      name: kafka_kafka-network
