version: '3'
services:
  delta-consumer:
    restart: always
    build:
      context: ./consumer
    networks:
      - kafka-network
networks:
  kafka-network:
    external:
      name:   kafka_kafka-network
